import { useState } from "react";
import { Eye, Download, CheckCircle, XCircle, FileText } from "lucide-react";
import { useApp } from "../../context/AppContext";
import { StatusBadge } from "../../components/ui/Badge";
import Badge from "../../components/ui/Badge";
import { ConfirmDialog } from "../../components/ui/Modal";
import type { QuestionPaper } from "../../types";

function PaperViewModal({ paper, onClose, onApprove, onReject }: {
  paper: QuestionPaper; onClose: () => void;
  onApprove: () => void; onReject: (reason: string) => void;
}) {
  const [confirmApprove, setConfirmApprove] = useState(false);
  const [confirmReject, setConfirmReject] = useState(false);
  const [rejectReason, setRejectReason] = useState("");

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal-box max-w-5xl mx-4 slide-in" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center justify-between p-5 border-b border-slate-100">
          <div>
            <h2 className="font-display text-lg font-700 text-slate-900">{paper.subjectName} — {paper.paperId}</h2>
            <p className="text-sm text-slate-500 mt-0.5">Generated by {paper.facultyName} · {paper.generatedDate}</p>
          </div>
          <div className="flex items-center gap-2">
            <StatusBadge status={paper.status} />
            <button onClick={onClose} className="ml-2 p-1.5 rounded-lg hover:bg-slate-100 text-slate-400">✕</button>
          </div>
        </div>

        <div className="flex overflow-hidden" style={{ maxHeight: "70vh" }}>
          {/* Paper content */}
          <div className="flex-1 overflow-y-auto p-6">
            {/* Exam header */}
            <div className="text-center border-b-2 border-slate-900 pb-4 mb-6">
              <h3 className="font-display text-lg font-700 text-slate-900 uppercase">Techno University</h3>
              <p className="text-sm font-600 text-slate-700 mt-1 uppercase tracking-wide">{paper.examType} Examination</p>
              <div className="mt-3 grid grid-cols-2 gap-x-8 text-sm text-slate-700 max-w-md mx-auto text-left">
                <div><span className="font-600">Subject:</span> {paper.subjectName}</div>
                <div><span className="font-600">Course Code:</span> {paper.courseCode}</div>
                <div><span className="font-600">Semester:</span> {paper.semester}</div>
                <div><span className="font-600">Date:</span> {paper.date}</div>
                <div><span className="font-600">Duration:</span> {paper.duration}</div>
                <div><span className="font-600">Max Marks:</span> {paper.totalMarks}</div>
              </div>
              <p className="text-xs text-slate-500 mt-3">Instructions: 1. Answer all questions. 2. Assume suitable data wherever required.</p>
            </div>

            {paper.sections.map((section) => (
              <div key={section.name} className="mb-6">
                <h4 className="font-display font-700 text-slate-900 mb-3">{section.name}</h4>
                {section.questions.map((q, qi) => (
                  <div key={q.id} className="mb-4 p-4 bg-slate-50 rounded-xl">
                    <div className="flex items-start justify-between gap-4">
                      <p className="text-sm text-slate-800 flex-1">
                        <span className="font-600">Q{qi + 1}.</span> {q.text}
                      </p>
                      <span className="text-sm font-600 text-slate-600 flex-shrink-0">[{q.marks} M]</span>
                    </div>
                    <div className="flex items-center gap-2 mt-2">
                      <Badge variant="purple" size="sm">{q.co}</Badge>
                      <Badge variant="info" size="sm">{q.po}</Badge>
                      <Badge variant="default" size="sm">{q.bloom}</Badge>
                      <Badge variant={q.difficulty === "Easy" ? "success" : q.difficulty === "Hard" ? "error" : "warning"} size="sm">{q.difficulty}</Badge>
                      <span className="text-xs text-amber-600 bg-amber-50 px-2 py-0.5 rounded-full">AI Generated — Review Required</span>
                    </div>
                  </div>
                ))}
              </div>
            ))}
          </div>

          {/* Validation panel */}
          <div className="w-64 border-l border-slate-200 p-5 overflow-y-auto bg-slate-50">
            <h3 className="font-display font-600 text-slate-900 mb-4 text-sm">Paper Validation</h3>
            <div className="space-y-2">
              {[
                { label: "Total marks satisfied", ok: true },
                { label: "CO coverage satisfied", ok: true },
                { label: "PO coverage satisfied", ok: true },
                { label: "Bloom distribution", ok: true },
                { label: "Difficulty distribution", ok: true },
                { label: "No duplicate questions", ok: true },
              ].map((v) => (
                <div key={v.label} className="validation-item">
                  {v.ok ? <CheckCircle size={14} className="check" /> : <XCircle size={14} className="fail" />}
                  <span className="text-xs text-slate-600">{v.label}</span>
                </div>
              ))}
              <div className="pt-2 border-t border-slate-200 mt-2 space-y-2">
                <p className="text-xs font-600 text-amber-600">Warnings</p>
                <div className="validation-item">
                  <span className="warn text-amber-500">⚠</span>
                  <span className="text-xs text-slate-600">CO3 underrepresented</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {paper.status === "Under Review" && (
          <div className="p-5 border-t border-slate-100 flex items-center gap-3 justify-end">
            <button className="btn-secondary" onClick={() => {}}>
              <Download size={15} /> Download PDF
            </button>
            <button className="btn-danger" onClick={() => setConfirmReject(true)}>
              <XCircle size={15} /> Reject
            </button>
            <button className="btn-primary" onClick={() => setConfirmApprove(true)}>
              <CheckCircle size={15} /> Approve Paper
            </button>
          </div>
        )}

        <ConfirmDialog
          open={confirmApprove}
          onClose={() => setConfirmApprove(false)}
          onConfirm={() => { onApprove(); onClose(); }}
          title="Approve this question paper?"
          message="The paper will be marked as approved and the faculty will be notified."
          confirmLabel="Approve Paper"
          confirmClass="btn-primary"
        />
        <ConfirmDialog
          open={confirmReject}
          onClose={() => setConfirmReject(false)}
          onConfirm={() => { onReject(rejectReason); onClose(); }}
          title="Send paper back for revision?"
          message="Please provide a reason so the faculty can make necessary corrections."
          confirmLabel="Send Back to Faculty"
          confirmClass="btn-danger"
          inputLabel="Reason for rejection"
          inputValue={rejectReason}
          onInputChange={setRejectReason}
        />
      </div>
    </div>
  );
}

export default function AdminQuestionPapers() {
  const { papers, updatePaper, toast } = useApp();
  const [viewPaper, setViewPaper] = useState<QuestionPaper | null>(null);

  const stats = {
    total: papers.length,
    draft: papers.filter((p) => p.status === "Draft").length,
    review: papers.filter((p) => p.status === "Under Review").length,
    approved: papers.filter((p) => p.status === "Approved").length,
  };

  return (
    <div className="p-6">
      <div className="mb-6">
        <h1 className="font-display text-2xl font-700 text-slate-900">Question Paper Review</h1>
        <p className="text-slate-500 mt-1 text-sm">Review and approve question papers generated by faculty.</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-4 gap-4 mb-6">
        {[
          { label: "Total Papers", value: stats.total, color: "text-slate-700 bg-slate-50 border-slate-200" },
          { label: "Draft", value: stats.draft, color: "text-slate-600 bg-slate-50 border-slate-200" },
          { label: "Under Review", value: stats.review, color: "text-amber-700 bg-amber-50 border-amber-200" },
          { label: "Approved", value: stats.approved, color: "text-green-700 bg-green-50 border-green-200" },
        ].map((s) => (
          <div key={s.label} className={`rounded-xl border p-4 ${s.color}`}>
            <p className="text-2xl font-display font-700">{s.value}</p>
            <p className="text-sm font-500 mt-0.5">{s.label}</p>
          </div>
        ))}
      </div>

      <div className="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="data-table">
            <thead>
              <tr>
                <th>Paper ID</th>
                <th>Subject</th>
                <th>Faculty</th>
                <th>Department</th>
                <th>Exam Type</th>
                <th>Date</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {papers.map((p) => (
                <tr key={p.id}>
                  <td><span className="font-mono-data text-xs bg-slate-100 text-slate-600 px-2 py-0.5 rounded">{p.paperId}</span></td>
                  <td>
                    <div className="font-500 text-slate-900">{p.subjectName}</div>
                    <div className="text-xs text-slate-400 font-mono-data">{p.courseCode}</div>
                  </td>
                  <td className="text-sm text-slate-700">{p.facultyName}</td>
                  <td><span className="text-xs text-slate-500">{p.department}</span></td>
                  <td><Badge variant="info" size="sm">{p.examType}</Badge></td>
                  <td className="text-xs text-slate-500">{p.date}</td>
                  <td><StatusBadge status={p.status} /></td>
                  <td>
                    <div className="flex items-center gap-1">
                      <button className="btn-ghost p-1.5" title="View" onClick={() => setViewPaper(p)}><Eye size={14} /></button>
                      <button className="btn-ghost p-1.5" title="Download"><Download size={14} /></button>
                      {p.status === "Under Review" && (
                        <>
                          <button
                            className="btn-ghost p-1.5 text-green-600 hover:bg-green-50"
                            title="Approve"
                            onClick={() => {
                              updatePaper({ ...p, status: "Approved" });
                              toast("success", `${p.paperId} approved.`);
                            }}
                          ><CheckCircle size={14} /></button>
                          <button
                            className="btn-ghost p-1.5 text-red-500 hover:bg-red-50"
                            title="Reject"
                            onClick={() => {
                              updatePaper({ ...p, status: "Rejected", rejectionReason: "Needs revision." });
                              toast("warning", `${p.paperId} sent back for revision.`);
                            }}
                          ><XCircle size={14} /></button>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {viewPaper && (
        <PaperViewModal
          paper={viewPaper}
          onClose={() => setViewPaper(null)}
          onApprove={() => {
            updatePaper({ ...viewPaper, status: "Approved" });
            toast("success", `${viewPaper.paperId} has been approved.`);
            setViewPaper(null);
          }}
          onReject={(reason) => {
            updatePaper({ ...viewPaper, status: "Rejected", rejectionReason: reason });
            toast("warning", `${viewPaper.paperId} sent back to ${viewPaper.facultyName} for revision.`);
            setViewPaper(null);
          }}
        />
      )}
    </div>
  );
}
